FORMAT: 1A
# Dredd example
## Addresses [/addresses]
### Create Address [POST]
+ Request (application/json)
    {
          "addressId": "1",
          "title": "Mrs",
          "firstName": "Varuna",
          "lastName": "Srivastava",
          "line1": "300 Front St West",
          "line2": "Blue building",
          "line3": "Box",
          "city": "Toronto",
          "state": "Ontario"
        }
+ Response 201 (application/json; charset=utf-8)
    + Headers
        content-type: application/json
    + Body
            {
                "addressId": 1
            }